'use client';

import { Box, Button, Container, Heading, Spinner, Stack, Text, Textarea } from '@chakra-ui/react';
import { Card } from '@chakra-ui/react';
import { useState } from 'react';
import { Toaster, toaster } from '@/components/ui/toaster';

export default function PlaceGPTTester() {
  const [prompt, setPrompt] = useState('');
  const [result, setResult] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSubmit = async () => {
    if (!prompt.trim()) {
      toaster.create({
        title: '프롬프트를 입력해주세요',
        description: 'GPT에게 전달할 분위기나 상황을 입력해야 추천이 가능합니다.',
        type: 'warning',
      });
      return;
    }

    setLoading(true);
    setResult('');

    try {
      const res = await fetch('/api/ai-recommend', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          location: '서울 노원구',
          timeLimit: 60,
          mood: prompt,
        }),
      });

      const data = await res.json();

      if (data.result) {
        setResult(data.result);
        toaster.create({
          title: '추천 성공',
          description: 'GPT가 장소를 추천했어요!',
          type: 'success',
        });
      } else {
        throw new Error();
      }
    } catch {
      toaster.create({
        title: '추천 실패',
        description: 'GPT로부터 응답을 받지 못했어요.',
        type: 'error',
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <Container maxW="lg" py={12}>
      <Stack gap={6}>
        <Heading size="lg" color="teal.600" textAlign="center">
          GPT 장소 추천 테스트
        </Heading>

        <Textarea
          placeholder="예: 혼자 조용히 쉴 수 있는 북카페"
          value={prompt}
          onChange={e => setPrompt(e.target.value)}
          _focus={{ borderColor: 'teal.400' }}
          borderRadius="md"
        />

        <Button onClick={handleSubmit} colorScheme="teal" size="md" loading={loading} loadingText="추천 받는 중...">
          GPT 추천 받기
        </Button>

        {loading && (
          <Box textAlign="center" pt={4}>
            <Spinner color="teal.500" size="lg" />
            <Text mt={2} fontSize="sm">
              GPT가 장소를 생각 중이에요...
            </Text>
          </Box>
        )}

        {result && (
          <Card.Root borderWidth="1px" borderColor="teal.300" borderRadius="xl" p={4}>
            <Card.Header>
              <Text fontWeight="bold" fontSize="lg" color="teal.600">
                GPT 추천 결과
              </Text>
            </Card.Header>
            <Card.Body>
              <Text fontSize="md" whiteSpace="pre-wrap">
                {result}
              </Text>
            </Card.Body>
            <Card.Footer justifyContent="flex-end">
              <Text fontSize="sm" color="gray.500">
                Generated by GPT-3.5
              </Text>
            </Card.Footer>
          </Card.Root>
        )}
      </Stack>

      {/* 최신 Chakra Toast 시스템 */}
      <Toaster />
    </Container>
  );
}
