export const PRIMARY_PLACES_CATEGORY = {
  tourist_attraction: '관광지',
  restaurant: '음식점',
  cafe: '카페',
  museum: '예술관',
  bar: '바&펍',
} as const;

export const PLACES_CATEGORY_COLOR_SET = {
  airport: { ko: '공항', color: 'blue' },
  amusement_park: { ko: '놀이공원', color: 'yellow' },
  aquarium: { ko: '아쿠아리움', color: 'teal' },
  art_gallery: { ko: '미술관', color: 'purple' },
  bakery: { ko: '빵집', color: 'orange' },
  bar: { ko: '바&펍', color: 'pink' },
  cafe: { ko: '카페', color: 'orange' },
  campground: { ko: '캠핑장', color: 'green' },
  casino: { ko: '카지노', color: 'red' },
  cemetery: { ko: '묘지', color: 'gray' },
  department_store: { ko: '백화점', color: 'cyan' },
  doctor: { ko: '병원', color: 'red' },
  church: { ko: '교회', color: 'gray' },
  library: { ko: '도서관', color: 'teal' },
  liquor_store: { ko: '주류 판매점', color: 'purple' },
  city_hall: { ko: '시청', color: 'gray' },
  lodging: { ko: '숙박업소', color: 'blue' },
  movie_theater: { ko: '영화관', color: 'purple' },
  museum: { ko: '박물관', color: 'purple' },
  night_club: { ko: '나이트클럽', color: 'pink' },
  park: { ko: '공원', color: 'green' },
  restaurant: { ko: '음식점', color: 'red' },
  meal_takeaway: { ko: '음식점', color: 'red' },
  shopping_mall: { ko: '쇼핑몰', color: 'cyan' },
  spa: { ko: '스파', color: 'pink' },
  zoo: { ko: '동물원', color: 'orange' },
  art_studio: { ko: '예술 작업실', color: 'purple' },
  natural_feature: { ko: '자연 명소', color: 'green' },
  historical_place: { ko: '역사적 장소', color: 'gray' },
  cultural_landmark: { ko: '문화 랜드마크', color: 'gray' },
  performing_arts_theater: { ko: '공연 예술 극장', color: 'purple' },
  monument: { ko: '기념물', color: 'gray' },
  stadium: { ko: '경기장', color: 'yellow' },
  tourist_attraction: { ko: '관광지', color: 'purple' },
  point_of_interest: { ko: '명소', color: 'orange' },
  parking: { ko: '주차장', color: 'gray' },
  grocery_or_supermarket: { ko: '식료품', color: 'gray' },
  bus_station: { ko: '버스정류장', color: 'gray' },
  home_goods_store: { ko: '수제품', color: 'gray' },
  clothing_store: { ko: '의류점', color: 'gray' },
  // 나머지 모든 타입은 기본 gray
  university: { ko: '대학교', color: 'gray' },
  secondary_school: { ko: '학교', color: 'gray' },
  store: { ko: '가게', color: 'gray' },
  transit_station: { ko: '환승역', color: 'gray' },
  gas_station: { ko: '주유소', color: 'gray' },
  police: { ko: '경찰서', color: 'gray' },
  post_office: { ko: '우체국', color: 'gray' },
  bank: { ko: '은행', color: 'gray' },
  convenience_store: { ko: '편의점', color: 'gray' },
  school: { ko: '학교', color: 'gray' },
  subway_station: { ko: '지하철역', color: 'gray' },
  train_station: { ko: '기차역', color: 'gray' },
  beauty_salon: { ko: '미용실', color: 'gray' },
  gym: { ko: '헬스장', color: 'gray' },
  pet_store: { ko: '애완동물 가게', color: 'gray' },
} as const;

export const DEFAULT_PLACES_CATEGORY = 'tourist_attraction';
